config/routes.rb
Rainforest::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :products
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
end

$end

app/models/product.rb
class Product < ActiveRecord::Base
	  attr_accessible :description, :name, :price_in_cents

	  validates :description, :name, :presence => true
	  validates :price_in_cents, :numericality => {:only_integer => true}

	  has_many :reviews
	  has_many :users, :through => :reviews

	  def formatted_price
	    price_in_dollars = price_in_cents.to_f / 100
	    sprintf("%.2f", price_in_dollars)
	  end

	class Review < ActiveRecord::Base
	  belongs_to :user
	  belongs_to :product
	end

	class User < ActiveRecord::Base
	  
	  has_many :reviews
	  has_many :products, :through => :reviews
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id  
  belongs_to :product
end

app/models/user.rb
# class User < ActiveRecord::Base
#   attr_accessible :email, :password_digest
# end 
#- this is what was created but has "password_digest" which it says it shouldn't have until data gets saved to the model (maybe it is saved?)
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name
  has_secure_password
  validates_presence_of :name, :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end
$end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	# use render :text => "Error found" and return to do printf-style debugging in your page (models are easy to debug from the console)
	# Use sessions to store data between requests: session[:variable] = “data” 
	# http://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 	<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>

    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>

</body>
</html>

app/views/products backup/_edit.html.erb
<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products backup/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products backup/index.html.erb
<h1>Products (<%= @products.length %>)</h1>
<%= link_to "New Product", "/products/new" %>

<% @products.each do |products| %>
	<p><%= link_to "Edit", "/products/edit" %> 
		Name: <%= products[:name] %>, Description: <%= products[:description] %>
  		Price in Cents: <%= products[:price_in_cents] %>
	</p>

  <%#= link_to image_tag(products.url), "/products/#{products.id}" %>
<% end %>

app/views/products backup/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products backup/show.html.erb
<%= link_to "Back to products", products_path %> | 
<%= link_to "Edit", edit_product_path(@product) %> | 
<%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>

<p><%= @product[:name] %>, <%= @product[:description] %></p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>List of Products</h1>

<% @products.each do |product| %>
<p><b>Name:</b> <%= product[:name] %><br>
<b>Description:</b> <%= product[:description] %><br>
<b>Price:</b> $<%= product.formatted_price %></p>
<% end %>

app/views/products/new.html.erb
<!-- h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p> -->
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p><%= link_to "Back to products", products_path %> |
<%= link_to "Edit", edit_product_path(@product) %> | </p>

<p><b>Name:</b> <%= @product[:name] %><br>
<b>Description:</b> <%= @product[:description] %><br>
<b>Price:</b> $<%= @product.formatted_price %></p>


<% if current_user %>

  <h3>Reviews</h3>

  <p>Reviews for <%= @product.name %></p>

  <% @product.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>
  <% end %>

app/views/users/create--no-test-framework.html.erb
<h1>Users#create--no-test-framework</h1>
<p>Find me in app/views/users/create--no-test-framework.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>